id: deploy_email_api
namespace: null.playbooks.deploy

inputs:
  - id: server_user
    type: STRING
    defaults: "devops"

variables:
  local_user: "murph"
  local_path: "/var"
  remote_base_path: "/home/{{ inputs.server_user }}"


tasks:
  - id: get_doppler_secret
    type: io.kestra.plugin.core.flow.Subflow
    namespace: doppler.secrets
    flowId: doppler_get_secret
    inputs:
      project_name: kestra
      config: dev
      secret_name: ANSIBLE_VARIABLES
    wait: true
    transmitFailed: true

  - id: deploy 
    type: io.kestra.plugin.ansible.cli.AnsibleCLI
    inputFiles:
      doppler-secrets.json: "{{ fromJson(outputs.get_doppler_secret.outputs.secret) }}"
    commands:
      - ansible-playbook -i /var/ansible/servers/inventory_a2hosting /var/ansible/workflows/jammy/deploy/email-api.yml --extra-vars "@doppler-secrets.json" -e "remote_base_path={{ vars.remote_base_path }}" -e "server_user={{ inputs.server_user }}" -e "local_path={{ vars.local_path }}" -vv
    env:
      USER: ansible
      MY_UID: "1000"
      MY_GID: "1000"
      ANSIBLE_CONFIG: /var/ansible/ansible.cfg
      SSH_AUTH_SOCK: /ssh-agent
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      user: ansible
      volumes:
        - /home/{{ vars.local_user }}/kestra/ansible:/var/ansible
        - /home/{{ vars.local_user }}/workspace:/var/workspace
        - /home/{{ vars.local_user }}/.ssh/:/home/ansible/.ssh/
        - "{{ envs.ssh_auth_sock }}:/ssh-agent"

