id: deploy_email_api
namespace: null.playbooks.deploy

inputs:
  - id: server_user
    type: STRING
    defaults: "devops"

  - id: env
    type: STRING
    defaults: dev

variables:
  local_user: "murph"
  project_name: kestra
  config: dev
  secret_name: ANSIBLE_VARIABLES
  local_path: "/var"
  remote_base_path: "/home/{{ inputs.remote_user }}"


tasks:
  - id: basic_auth_api
    type: io.kestra.plugin.core.http.Request
    uri: https://api.doppler.com/v3/configs/config/secret?project={{ vars.project_name }}&config={{ vars.config}}&name={{ vars.secret_name }}
    encryptBody: true
    headers:
      accept: application/json
      authorization: "Bearer {{ secret('DOPPLER_TOKEN') }}"

  - id: deploy 
    type: io.kestra.plugin.ansible.cli.AnsibleCLI
    inputFiles:
      doppler-secrets.json: "{{ fromJson(outputs.basic_auth_api.encryptedBody).value.raw }}"
    commands:
      - ansible-playbook -i /var/ansible/servers/inventory_a2hosting /var/ansible/workflows/jammy/deploy/email-api.yml --extra-vars "@doppler-secrets.json" -e "remote_base_path={{ vars.remote_base_path }}" -e "server_user={{ inputs.server_user }}" -e "env={{ inputs.env }}" -e "local_path={{ vars.local_path }}" -vv
    env:
      USER: ansible
      MY_UID: "1000"
      MY_GID: "1000"
      ANSIBLE_CONFIG: /var/ansible/ansible.cfg
      SSH_AUTH_SOCK: /ssh-agent
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      user: ansible
      volumes:
        - /home/{{ vars.local_user }}/kestra/ansible:/var/ansible
        - /home/{{ vars.local_user }}/workspace:/var/workspace
        - /home/{{ vars.local_user }}/.ssh/:/home/ansible/.ssh/
        - "{{ envs.ssh_auth_sock }}:/ssh-agent"

