id: update_nginx_configs
namespace: null.playbooks.configs

inputs:
  - id: envs
    type: ARRAY
    itemType: STRING
    defaults: ["local_user=murph", "local_path=/var", "remote_base_path=/home/devops"]


tasks:
  - id: get_doppler_secret
    type: io.kestra.plugin.core.flow.Subflow
    namespace: doppler.secrets
    flowId: doppler_get_secret
    inputs:
      project_name: kestra
      config: dev
      secret_name: ANSIBLE_VARIABLES
    wait: true
    transmitFailed: true

  - id: run_ansible_workflow
    type: io.kestra.plugin.core.flow.Subflow
    namespace: null
    flowId: ansible_base
    inputs:
      inventory_path: "/var/ansible/servers/inventory_a2hosting"
      workflow_path: "/var/ansible/playbooks/jammy/deploy/configs/update_nginx_configs.yml"
      doppler_secrets: "{{ fromJson(outputs.get_doppler_secret.outputs.secret) }}"
      envs: "{{ inputs.envs }}"
      local_user: "murph"
    wait: true
    transmitFailed: true
